<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 25.05.2017
 * Time: 17:01
 */

namespace app\controllers;
use Yii;

class PostController extends AppController
{
    public $layout = 'basic';

    public function beforeAction($action)
    {
        if($action->id == 'index'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        if( Yii::$app->request->isAjax ) {
            echo "POST: ";
            debug($_POST);
            debug(Yii::$app->request->post());
            return "test";
        }
        return $this->render('test');
    }
    public function actionShow(){
        //$this->layout = 'basic';
        return $this->render('show');
    }
}