<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 25.05.2017
 * Time: 17:01
 */

namespace app\controllers;
use app\models\Category;
use app\models\TestForm;
use Yii;

class PostController extends AppController
{
    public $layout = 'basic';

    public function beforeAction($action)
    {
        if($action->id == 'index'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex(){
        if( Yii::$app->request->isAjax ) {
            echo "POST: ";
            debug($_POST);
            debug(Yii::$app->request->post());
            return "test";
        }

        $model = new TestForm();
        if( $model->load( Yii::$app->request->post()) ){
//            debug(Yii::$app->request->post());
//            debug($model);
//            die;
            if( $model->validate() ) {
                Yii::$app->session->setFlash('success', 'Данные приняты');
                return $this->refresh();
            }
            else {
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }

        $this->view->title = "Все статьи";
        return $this->render('test', compact('model'));
    }


    public function actionShow(){
        //$this->layout = 'basic';
        $this->view->title = "Одна статья";
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы...']);

        $cats = Category::find()->all();

        return $this->render('show', compact('cats'));
    }
}