<?php
/**
 * Created by PhpStorm.
 * User: WolfGrin
 * Date: 29.05.2017
 * Time: 3:38
 */

namespace app\components;

use yii\base\Widget;

class MyWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //if( $this->name === null ) $this->name = 'Гость';

        ob_start();
    }

    public function run(){
        //return "<h1>{$this->name}, hello world!</h1>";
        //return $this->render('my', ['name' => $this->name]);

        $content = ob_get_clean();
        $content = mb_strtoupper($content);
        return $this->render('my', compact('content'));
    }
}